apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: notes
    tier: backend
spec:
  selector:
    app: notes
    tier: backend
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
