apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: notes-app
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # "postgres" encoded in base64
  POSTGRES_USER: cG9zdGdyZXM=      # "postgres" encoded in base64
  POSTGRES_DB: bm90ZXNfZGI=        # "notes_db" encoded in base64
