apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  labels:
    app: notes
    tier: database
spec:
  serviceName: "database"
  replicas: 1
  selector:
    matchLabels:
      app: notes
      tier: database
  template:
    metadata:
      labels:
        app: notes
        tier: database
    spec:
      containers:
      - name: postgres
        image: ${ACR_NAME}.azurecr.io/notes-database:${IMAGE_TAG}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "notesdb"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-premium"
      resources:
        requests:
          storage: 5Gi
