apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: notes
    tier: frontend
spec:
  selector:
    app: notes
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
